apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec: # Especificação geral
  selector:
    app: flask-app
  ports:
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
  type: LoadBalancer